#!/usr/bin/env bash
set -e
DIR="$(dirname "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )")"

echo $BUILD_ARGS

build_with_upstream_tag() {
  UPSTREAM_TAG=$1
  docker build "$DIR" $BUILD_ARGS -t deaddev/ubuntu-base:$UPSTREAM_TAG --build-arg UPSTREAM_TAG=$UPSTREAM_TAG
}

if [[ -z "UPSTREAM_TAG" ]]; then
  build_with_upstream_tag 20.04
  build_with_upstream_tag 21.04
else
  build_with_upstream_tag ${UPSTREAM_TAG}
  docker tag deaddev/ubuntu-base:${UPSTREAM_TAG} deaddev/ubuntu-base:latest
fi

